// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ReadingIsGood.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ReadingIsGood.Data.Migration
{
    [DbContext(typeof(DataContext))]
    [Migration("20210618123506_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ReadingIsGood.Data.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 780, DateTimeKind.Utc).AddTicks(4928),
                            Deleted = false,
                            Name = "Self-Help",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 780, DateTimeKind.Utc).AddTicks(5161)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 781, DateTimeKind.Utc).AddTicks(5370),
                            Deleted = false,
                            Name = "Biographies",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 781, DateTimeKind.Utc).AddTicks(5375)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 781, DateTimeKind.Utc).AddTicks(5446),
                            Deleted = false,
                            Name = "Business & Money",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 781, DateTimeKind.Utc).AddTicks(5447)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 781, DateTimeKind.Utc).AddTicks(5461),
                            Deleted = false,
                            Name = "Children's Books",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 781, DateTimeKind.Utc).AddTicks(5462)
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 781, DateTimeKind.Utc).AddTicks(5475),
                            Deleted = false,
                            Name = "History",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 781, DateTimeKind.Utc).AddTicks(5476)
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 781, DateTimeKind.Utc).AddTicks(5495),
                            Deleted = false,
                            Name = "Health, Fitness & Dieting",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 781, DateTimeKind.Utc).AddTicks(5496)
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 781, DateTimeKind.Utc).AddTicks(5508),
                            Deleted = false,
                            Name = "Politics & Social Sciences",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 781, DateTimeKind.Utc).AddTicks(5509)
                        });
                });

            modelBuilder.Entity("ReadingIsGood.Data.Entity.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 783, DateTimeKind.Utc).AddTicks(2344),
                            Deleted = false,
                            FirstName = "Erçin",
                            LastName = "Dedeoğlu",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 783, DateTimeKind.Utc).AddTicks(2347)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 783, DateTimeKind.Utc).AddTicks(3090),
                            Deleted = false,
                            FirstName = "Aylin",
                            LastName = "Dedeoğlu",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 783, DateTimeKind.Utc).AddTicks(3092)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 783, DateTimeKind.Utc).AddTicks(3108),
                            Deleted = false,
                            FirstName = "Ata",
                            LastName = "Dedeoğlu",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 783, DateTimeKind.Utc).AddTicks(3110)
                        });
                });

            modelBuilder.Entity("ReadingIsGood.Data.Entity.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ReadingIsGood.Data.Entity.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderDetailStatus")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("ReadingIsGood.Data.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AmountOfStock")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOfStock = 13,
                            CategoryId = 1,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(8400),
                            Deleted = false,
                            Name = "Color Joy Coloring Book: Perfectly Portable Pages",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(8403)
                        },
                        new
                        {
                            Id = 2,
                            AmountOfStock = 3,
                            CategoryId = 1,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9008),
                            Deleted = false,
                            Name = "The Four Agreements: A Practical Guide to Personal Freedom",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9010)
                        },
                        new
                        {
                            Id = 3,
                            AmountOfStock = 0,
                            CategoryId = 1,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9031),
                            Deleted = false,
                            Name = "Greenlights",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9032)
                        },
                        new
                        {
                            Id = 4,
                            AmountOfStock = 1881,
                            CategoryId = 2,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9047),
                            Deleted = false,
                            Name = "Atatürk",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9048)
                        },
                        new
                        {
                            Id = 5,
                            AmountOfStock = 55,
                            CategoryId = 2,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9063),
                            Deleted = false,
                            Name = "12 Years a Slave",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9063)
                        },
                        new
                        {
                            Id = 6,
                            AmountOfStock = 233,
                            CategoryId = 2,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9081),
                            Deleted = false,
                            Name = "Running on Red Dog Road: And Other Perils of an Appalachian",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9082)
                        },
                        new
                        {
                            Id = 7,
                            AmountOfStock = 233,
                            CategoryId = 3,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9145),
                            Deleted = false,
                            Name = "The Book on Sales and Marketing: Expert Marketing for the People",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9146)
                        },
                        new
                        {
                            Id = 8,
                            AmountOfStock = 233,
                            CategoryId = 3,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9161),
                            Deleted = false,
                            Name = "HBR's 10 Must Reads on Sales",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9162)
                        },
                        new
                        {
                            Id = 9,
                            AmountOfStock = 233,
                            CategoryId = 3,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9176),
                            Deleted = false,
                            Name = "Sales 101: From Finding Leads and Closing Techniques to Retaining Customers and Growing Your Business",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9177)
                        },
                        new
                        {
                            Id = 10,
                            AmountOfStock = 233,
                            CategoryId = 4,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9192),
                            Deleted = false,
                            Name = "Lost on a Mountain in Maine",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9193)
                        },
                        new
                        {
                            Id = 11,
                            AmountOfStock = 233,
                            CategoryId = 4,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9207),
                            Deleted = false,
                            Name = "The Boy on the Wooden Box: How the Impossible Became Possible",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9208)
                        },
                        new
                        {
                            Id = 12,
                            AmountOfStock = 233,
                            CategoryId = 4,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9221),
                            Deleted = false,
                            Name = "A Long Walk to Water: Based on a True Story",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9222)
                        },
                        new
                        {
                            Id = 13,
                            AmountOfStock = 233,
                            CategoryId = 5,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9236),
                            Deleted = false,
                            Name = "The Turkish War of Independence: A Military History, 1919-1923",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9237)
                        },
                        new
                        {
                            Id = 14,
                            AmountOfStock = 233,
                            CategoryId = 5,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9250),
                            Deleted = false,
                            Name = "The Happiest Man on Earth",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9251)
                        },
                        new
                        {
                            Id = 15,
                            AmountOfStock = 233,
                            CategoryId = 5,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9264),
                            Deleted = false,
                            Name = "Wild: From Lost to Found on the Pacific Crest Trail",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9265)
                        },
                        new
                        {
                            Id = 16,
                            AmountOfStock = 233,
                            CategoryId = 6,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9278),
                            Deleted = false,
                            Name = "The Good Carb Cookbook: Secrets of Eating Low on the Glycemic Index",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9279)
                        },
                        new
                        {
                            Id = 17,
                            AmountOfStock = 233,
                            CategoryId = 6,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9292),
                            Deleted = false,
                            Name = "The Four Agreements: A Practical Guide to Personal Freedom",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9293)
                        },
                        new
                        {
                            Id = 18,
                            AmountOfStock = 233,
                            CategoryId = 6,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9307),
                            Deleted = false,
                            Name = "Quiet: The Power of Introverts in a World That Can't Stop Talking",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9309)
                        },
                        new
                        {
                            Id = 19,
                            AmountOfStock = 233,
                            CategoryId = 7,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9321),
                            Deleted = false,
                            Name = "Spilled Milk: Based on a true story",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9322)
                        },
                        new
                        {
                            Id = 20,
                            AmountOfStock = 233,
                            CategoryId = 7,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9335),
                            Deleted = false,
                            Name = "Exposing U.S. Government Policies On Extraterrestrial Life: The Challenge Of Exopolitics",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9336)
                        },
                        new
                        {
                            Id = 21,
                            AmountOfStock = 233,
                            CategoryId = 7,
                            CreateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9349),
                            Deleted = false,
                            Name = "On Death And Dying",
                            UpdateDate = new DateTime(2021, 6, 18, 12, 35, 5, 782, DateTimeKind.Utc).AddTicks(9350)
                        });
                });

            modelBuilder.Entity("ReadingIsGood.Data.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ReadingIsGood.Data.Entity.Order", b =>
                {
                    b.HasOne("ReadingIsGood.Data.Entity.Customer", "Customer")
                        .WithMany("OrderDetails")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ReadingIsGood.Data.Entity.OrderDetail", b =>
                {
                    b.HasOne("ReadingIsGood.Data.Entity.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReadingIsGood.Data.Entity.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ReadingIsGood.Data.Entity.Product", b =>
                {
                    b.HasOne("ReadingIsGood.Data.Entity.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ReadingIsGood.Data.Entity.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ReadingIsGood.Data.Entity.Customer", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ReadingIsGood.Data.Entity.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ReadingIsGood.Data.Entity.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
